### ISSUE TITLE
Arrow keys aren't working

### ISSUE THREAD

**Issue by YonatanKra** [FountainJS/generator-fountain-inject#20]
Hi,
I've been using gulp-angular for a long time and it's great. Fountain looks awesome as well.
I've started installing and the arrow keys didn't work for me (when needed to choose angular/react/ng2).
Any idea why?
A work around (if arrows don't work) is to type a number (e.g. `2` for `angular 2`).

**Comment by Swiip** [comment]
Never seen this. And the choices are powered by inquirer exactly the same way than in gulp-angular.

Can you post this in generator-fountain-webapp, or perhaps even directly in inquirer ?

**Comment by pdemro** [comment]
I noticed this issue today when I tried to use the generator with Git Bash for Windows.  Could not use arrow keys on the first stage (select Javascript framework).

Workaround is to use CMD
